# Generated by Django 5.0.6 on 2024-06-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_market_email_market_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='default_password_value', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='password',
            field=models.CharField(default='default_password_value', max_length=255),
        ),
    ]
