# Generated by Django 5.0.6 on 2024-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Others', max_length=64),
        ),
    ]
