# Generated by Django 5.0.6 on 2024-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='plate_number',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
